# Generated by Django 3.1 on 2020-11-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientinfo_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientDetail',
        ),
        migrations.DeleteModel(
            name='detail',
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='pin',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='primary_contact',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='secondary_contact',
            field=models.IntegerField(max_length=15),
        ),
    ]
