# Generated by Django 3.1 on 2020-11-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201128_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='pin',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='primary_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='secondary_contact',
            field=models.CharField(max_length=15),
        ),
    ]
