# Generated by Django 3.1 on 2020-11-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientdetail_detail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientdetail',
            table=None,
        ),
    ]
