# Generated by Django 3.1 on 2020-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20201129_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinformation',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='unique_id',
            field=models.CharField(default=True, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
