# Generated by Django 3.1 on 2020-11-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20201130_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinformation',
            name='image',
        ),
    ]
