# Generated by Django 3.1 on 2020-09-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0003_delivard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivard',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
