# Generated by Django 3.1 on 2020-09-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0004_auto_20200902_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivard',
            name='date',
        ),
        migrations.RemoveField(
            model_name='delivard',
            name='user',
        ),
    ]
