# Generated by Django 3.1 on 2020-11-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0005_auto_20200902_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
