# Generated by Django 3.1 on 2020-11-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0008_auto_20201121_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='itemadd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
