# Generated by Django 3.1 on 2020-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0010_product_makername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='makername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
