# Generated by Django 3.1 on 2020-12-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0011_auto_20201227_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='book',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
