# Generated by Django 3.1 on 2020-12-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0012_product_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='book',
            new_name='booking',
        ),
    ]
