# Generated by Django 3.1 on 2020-12-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0013_auto_20201228_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
