# Generated by Django 3.1 on 2021-01-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20201214_1546'),
        ('reglog', '0014_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clientInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.clientinformation'),
        ),
    ]
