# Generated by Django 3.1 on 2021-01-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0015_product_clientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
