# Generated by Django 3.1 on 2021-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0018_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
