# Generated by Django 3.1 on 2021-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0021_reviewproduct_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduct',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
